# Generated by Django 4.2.1 on 2023-07-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0002_alter_student_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='std_name',
        ),
    ]
