# Generated by Django 4.2.1 on 2023-08-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0003_rename_name_student_std_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='medium',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
