# Generated by Django 4.2.1 on 2023-08-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0005_alter_school_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='medium',
            field=models.CharField(choices=[('KA', 'kannada'), ('EG', 'english'), ('HI', 'hindi')], default='English', max_length=100),
        ),
    ]
