# Generated by Django 4.2.1 on 2023-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0006_alter_school_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='medium',
            field=models.CharField(choices=[('EG', 'english'), ('KA', 'kannada'), ('HI', 'hindi')], default='English', max_length=100),
        ),
    ]
